FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./

RUN npm ci --include=dev

COPY apps/gateway ./apps/gateway

RUN npm run build gateway

FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY --from=builder /app/dist/apps/gateway ./dist/apps/gateway

EXPOSE 3000

CMD ["node", "dist/apps/gateway/main.js"]
